os: windows
language: shell
before_install:
  - choco install python --version=3.9
  - python -m pip install --upgrade pip
env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
install:
  - pip install -r requirements.txt
  - pip install pyinstaller
script:
  - echo "Done"
before_deploy:
  - pyinstaller --onefile --noconsole --name Anatool main.py
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file: dist/*.exe
  skip_cleanup: true
  draft: true
